### ISSUE TITLE
UnboundLocalError: local variable 'vols1' referenced before assignment

### ISSUE THREAD

**Issue by taariq** [VolumeFi/trading-bots#2]
trading-bots: python3.9 MomentumScanner.py
no query
Traceback (most recent call last):
  File "/trading-bots/MomentumScanner.py", line 90, in <module>
    findbestreturn(dex='apeswap_bsc')
  File "/trading-bots/MomentumScanner.py", line 78, in findbestreturn
    rets24h = findrets24h(vols1)
UnboundLocalError: local variable 'vols1' referenced before assignment

**Comment by fieldtheory123** [comment]
I think this is because the API endpoint returned no value. 
I updated the script and it doesn't error out if query returns no value. If you get a "no query", wait for a few seconds and run again.
