### ISSUE TITLE
FE queries are running very slow

### ISSUE THREAD

**Issue by fieldtheory123** [VolumeFi/trading-bots#23]
The FE queries sometimes take 30 seconds. 
I think the issue is that the BE is querying CG upon a FE request every time. If so, that needs to be changed. For most FE queries, the response should come from the DB directly which will be much faster. Also we do not need to update the DB that often.

Here is my proposal:
1. Rewrite the API so FE requests all come from the DB
2. Create a new function solely for updating the DB with the newest data. We can run a cron to update every a few hours

**Comment by taariq** [comment]
@measure-fi see my Loom on this experience here: https://www.loom.com/share/1f2e2466f93446f5b901b250e9412973

**Comment by verabehr** [comment]
moved to Paloma board https://github.com/VolumeFi/paloma/issues/229
