### ISSUE TITLE
Can't import findbestreturn

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/trading-bots#3]
I'm able to run `Momentumscanner.py`, but I can't use it for other dex's 

``` 
$ from MomentumScanner import findbestreturn
from: can't read /var/mail/MomentumScanner
```

```
from MomentumScanner import findbestreturn print(findbestreturn('apeswap'))
-bash: syntax error near unexpected token `('
```

**Comment by fieldtheory123** [comment]
Did you run 
``
$ from MomentumScanner import findbestreturn
``
from a python interpreter? If so, you need to go to the folder where you put Momentumscanner.py first

``
from MomentumScanner import findbestreturn print(findbestreturn('apeswap'))
-bash: syntax error near unexpected token `('
``
This looks like you ran it it a terminal. You will need to run it in a python interpreter. Try this in a terminal:

$cd directory-where-you-have-the-script
$python -i
$from MomentumScanner import findbestreturn
$print(findbestreturn('pancakeswap_new'))

**Comment by verabehr** [comment]
got it, thanks will try that. I did not run it from an interpreter

**Comment by verabehr** [comment]
interpreter worked and new instructions work even better 😄  closing
