### ISSUE TITLE
Bot Labels

### ISSUE THREAD

**Issue by joycehermosilla** [VolumeFi/trading-bots#32]
**LIMIT ORDER BOT:**
- [x] Limit Order Bot: As a user, I want to select the token that I will Buy with and the token that I will sell with. 

![Image](https://github.com/VolumeFi/trading-bots/assets/22323189/19679d9f-d340-49e7-89e9-c998390e8700)

- [x] Limit Order Bot: As a user, I want to see a Limit Ratio between the 2 selected tokens as the example: 
![Image](https://github.com/VolumeFi/trading-bots/assets/22323189/593d996b-4c8e-4d6a-9a7b-24a28f8a1dfb)

- [x] Limit Order Bot: For now, we will hide the Bot Duration.

**STOP LOSS BOT:**
- [x] Stop Loss Bot: Same that LOB the user will select the token to Buy with and the token to sell with. 
![Image](https://github.com/VolumeFi/trading-bots/assets/22323189/7387e27f-652b-4860-9b8b-3c746992d081)

- [x] Stop Loss Bot: We want to see under the Sell with a token the stop Loss ratio.
![Image](https://github.com/VolumeFi/trading-bots/assets/22323189/0511fed5-58b6-4fbf-b409-9cf17674cfae)

- [x] Stop Loss Bot: We want to hide the Bot Duration for now. 

**MOMENTUM BOT:**

- [x] We want to unify the labels to all our Bots so we will change the labels to BUY and SELL
![Image](https://github.com/VolumeFi/trading-bots/assets/22323189/933d2303-64ab-4466-a116-67b55b5b2ec1)

**DCA BOT**
- [x] For the DCA Bot the labels will also change to BUY and SELL.
![Image](https://github.com/VolumeFi/trading-bots/assets/22323189/2c98c380-b30f-49fa-98b6-fe1f1347cd87)

**Comment by jamie088** [comment]
@joycehermosilla @verabehr How about swapping Buy and Sell position in Limit order and Stop loss bot like this?

![Image](https://github.com/VolumeFi/trading-bots/assets/83244763/d2b50681-cb30-4cb0-8994-9decb7c34e35)

**Comment by verabehr** [comment]
yes I agree with that @jamie088 @joycehermosilla
