### ISSUE TITLE
Search by token for Paloma BOT

### ISSUE THREAD

**Issue by joycehermosilla** [VolumeFi/trading-bots#35]
As a user, I want to be able to go to PalomaBot and search by token and then create a bot on the selected bot.

- [ ] We want to add a new menu item to the Landing Page: "Seach Token". Will be the first item on the menu.
![Image](https://github.com/VolumeFi/trading-bots/assets/22323189/d34d9f75-e50e-4335-a79d-8cfc5563d602)

- [ ] We will show all tokens that are available in Coin Gecko with Price, (price) Change, TVL and Volume. The user will be able to sort by all these items using the arrows.

Design: https://www.figma.com/file/ClniQyKFqN1hSpWizV5O4A/Paloma?type=design&node-id=9175-58604&mode=design&t=9hJGJF7DwEZbDpc9-4
![Image](https://github.com/VolumeFi/trading-bots/assets/22323189/548ecfbd-3a86-43a0-b8dc-de638dd3cddf)

- [ ] If the user selects one of the tokens we will redirect them to a "Token Detail View"
Design: https://www.figma.com/file/ClniQyKFqN1hSpWizV5O4A/Paloma?type=design&node-id=9196-66770&mode=design&t=9hJGJF7DwEZbDpc9-4

- [ ] On the Token Detail View we want to see the Token Graphic (Momentum), Current Price, 24 Hr Volume, Market Cap, and Fully Diluted Market Valuation.

- [ ] On the right side the user will be able to select a build Bot (LOB, DCA, Stop Loss). After the user click on one of them, they will be redirected to the Create Bot page where the selected token will be the target token. 

![Image](https://github.com/VolumeFi/trading-bots/assets/22323189/d49140f0-fecb-4bc1-b46a-47e90b25a95d)

![Image](https://github.com/VolumeFi/trading-bots/assets/22323189/54364a6c-6a9d-4468-b910-047b626b157d)

**Comment by taariq** [comment]
@joycehermosilla will you move this to Paloma repo please.
