### ISSUE TITLE
BUG: run_momentum_table.py pulling in strange numbers and not complete table for Uniswap v3

### ISSUE THREAD

**Issue by taariq** [VolumeFi/trading-bots#8]
Running `python3 run_momentum_table.py uniswap_v3 12 200000 200000 2000000` returns `{}`
Further tests  on daily liquidity show the following:
```
1 => {}
100=> {hex}
1000 => {USDT, DAI, USDC}
10000 => {USDC}
```
Is there a problem with the API?

Coingecko API Calls History:
* Total Monthly API Calls: 24,584 / 500,000
* Remaining monthly API Calls: 475,416

**Comment by fieldtheory123** [comment]
I think it was the selloff in the past 12 hours. Everything was down so no tokens with +% return and thus no return tables. 

If there's no positive returns the table will be empty.

**Comment by taariq** [comment]
Closing for now.
